@startuml
class GitPushCommandItem {
    + Branch : string = "main"
    + <<override>> Clone() : object
    + GitPushCommandItem(workingDirectory:string, branch:string)
}
GitCommandItemBase <|-- GitPushCommandItem
@enduml
